name: 💡 Feature Request
description: Suggest an idea or enhancement
title: "[Feature] <Short feature title>"
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
      description: Describe the feature, UI impact, or config options
  - type: textarea
    id: why
    attributes:
      label: Why is it useful?
      description: What is the motivation for this feature?
