- device:
    friendly_name: Pool Heatpump
    tuya_device_id: eb27838708a77766e8gkx9
    tuya_product_id: edcxde1oraigz7tw
    tuya_category: znrb
    poll_interval: 300
    version: 1
    enabled: true

- climate:
    unique_id: pool_thermostat
    enabled: true
    scale: 1   # means raw = real degrees, no tenths
    current_temperature:
      code: temp_current_f
      dp: '35'
      type: integer
      add_separate_entity: true
    target_temperature:
      code: set_temp59_104
      dp: '196'
      type: integer
      min_temp: 59
      max_temp: 104
      precision: 1
    on_off:
      code: switch
      dp: '1'
      type: boolean
    hvac_mode:
      code: work_mode
      dp: '5'
      type: enum
      modes:
        heat: '1'
        cool: '0'

- sensor:
    code: work_state
    dp: '17'
    enabled: true
    type: enum
    entity_category: diagnostic
    translated:
      '1': 'standby'
      '2': 'heating'
      '3': 'warm'
      '4': '4'
      '5': 'cool'
      '6': '6'
      '7': '7'

- sensor:
    code: V_04
    dp: '104'
    name: E-E-V
    entity_category: diagnostic

- sensor:
    code: V_5
    name: "Coil Temperature"
    dp: '105'
    type: integer
    device_class: temperature
    unit_of_measurement: '°F'
    enabled: true

- sensor:
    code: V_6
    name: "Ambient Temperature"
    dp: '106'
    type: integer
    device_class: temperature
    unit_of_measurement: '°F'
    enabled: true

- sensor:
    code: V7
    name: "Suction Temperature"
    dp: '107'
    type: integer
    device_class: temperature
    unit_of_measurement: '°F'
    enabled: true

- sensor:
    code: V8
    name: "Exhaust Temperature"
    dp: '108'
    type: integer
    device_class: temperature
    unit_of_measurement: '°F'
    enabled: true

- sensor:
    code: V10
    name: "Outlet Temperature"
    dp: '110'
    type: integer
    device_class: temperature
    unit_of_measurement: '°F'
    enabled: true

- sensor:
    code: fault
    dp: '15'
    type: bitfield
    translated:
      0: 'No Fault'
      1: 'Water Flow!'
    entity_category: diagnostic
    enabled: true
