- device:
    friendly_name: Pool Pump
    tuya_device_id: ebeda6045c6efa0743ckr5
    tuya_product_id: ylymu5v6xscoveek
    tuya_category: cz    
    poll_interval: 300
    version: 1
    enabled: true
    
- switch:
    code: switch_1
    name: Power
    dp: '1'
    type: boolean
    restore_on_reconnect: true
    enabled: true

- sensor:
    code: relay_status
    dp: '38'
    type: enum
    translated:
      power_off: 'Off'
      power_on: 'On'
      last: 'Last State'
    enabled: true
