- device:
    friendly_name: Thermostat Upstairs
    tuya_device_id: ebbc33438cf6370a5fw9mg
    category: wk
    poll_interval: 60
    version: 1
    enabled: true

- climate:
    unique_id: upstairs_thermostat
    current_temperature_code: temp_current
    current_temperature_dp: '24'
    current_temperature_type: integer
    temperature_unit: '°F'
    target_temperature_code: temp_set
    target_temperature_dp: '16'
    target_temperature_type: integer
    switch_code: switch
    switch_id: '1'
    switch_type: boolean
    hvac_modes_code: mode
    hvac_modes_id: '2'
    hvac_modes_type: enum
    hvac_modes:
      off: manual
      heat: auto
    min_temp: 40
    max_temp: 90
    precision: 1
    enabled: true

- switch:
    code: child_lock
    id: '40'
    type: boolean
    restore_on_reconnect: false
    is_passive_entity: false
    entity_category: config
    enabled: true

- number:
    code: backlight
    id: '44'
    type: integer
    min_value: 0
    max_value: 100
    step_size: 1
    unit_of_measurement: '%'
    restore_on_reconnect: false
    is_passive_entity: false
    entity_category: config
    enabled: true

- sensor:
    code: valve_state
    id: '36'
    type: enum
    enabled: true

- sensor:
    code: battery_percentage
    id: '35'
    type: integer
    entity_category: diagnostic
    device_class: battery
    unit_of_measurement: '%'
    enabled: true
