- device:
    tuya_device_id: ebbc33438cf6370a5fw9mg
    local_ip: 192.168.68.189
    local_key: #mFM/Z;L.eI#P()r
    category: wk
    poll_interval: 270
    version: 1
    enabled: true

- climate:
    unique_id: upstairs_thermostat
    current_temperature_code: temp_current
    current_temperature_dp: '24'
    temperature_unit: '°F'
    target_temperature_code: temp_set
    target_temperature_dp: '16'
    switch_code: switch
    switch_dp: '1'
    hvac_modes_code: mode
    hvac_modes_dp: '2'
    hvac_modes:
      off: manual
      heat: auto
    min_temp: 59.0
    max_temp: 104.0
    precision: 1.0
    enabled: true

- switch:
    code: child_lock
    id: '40'
    restore_on_reconnect: false
    is_passive_entity: false
    enabled: true

- switch:
    code: backlight
    id: '44'
    restore_on_reconnect: false
    is_passive_entity: false
    enabled: true

- switch:
    code: eco
    id: '4'
    restore_on_reconnect: false
    is_passive_entity: false
    enabled: false

- switch:
    code: frost
    id: '10'
    restore_on_reconnect: false
    is_passive_entity: false
    enabled: false

- sensor:
    code: valve_state
    id: '36'
    enabled: true

- sensor:
    code: battery_percentage
    id: '35'
    entity_category: diagnostic
    device_class: battery
    enabled: true
