- device:
    friendly_name: Thermostat Upstairs
    tuya_device_id: ebbc33438cf6370a5fw9mg
    tuya_category: wk
    poll_interval: 60
    version: 1
    enabled: true

- climate:
    unique_id: upstairs_thermostat
    enabled: true
    temp_convert: "c_to_f"
    current_temperature:
      code: temp_current
      dp: '24'
      type: integer
    target_temperature:
      code: temp_set
      dp: '16'
      type: integer
      min_temp: 40
      max_temp: 90
      precision: 1
    on_off:
      code: switch
      dp: '1'
      type: boolean
    hvac_mode:
      code: mode
      dp: '2'
      type: enum
      modes:
        heat: 'manual'
        # heat_cool: 'auto'

- switch:
    code: child_lock
    dp: '40'
    type: boolean
    restore_on_reconnect: false
    is_passive_entity: false
    entity_category: config
    enabled: true

- number:
    code: backlight
    dp: '44'
    type: integer
    min_value: 0
    max_value: 100
    step_size: 1
    unit_of_measurement: '%'
    restore_on_reconnect: false
    is_passive_entity: false
    entity_category: config
    enabled: true

- sensor:
    code: valve_state
    dp: '36'
    type: enum
    translated:  # Optional: Translated values for the enum
      open: 'Heating'
      close: 'Off'
    enabled: true

- sensor:
    code: battery_percentage
    dp: '35'
    type: integer
    entity_category: diagnostic
    device_class: battery
    unit_of_measurement: '%'
    enabled: true
