- device:
    ha_name: thermostat-upstairs
    friendly_name: Upstairs Thermostat
    tuya_device_id: ebbc33438cf6370a5fw9mg
    local_ip: 192.168.68.189
    local_key: #mFM/Z;L.eI#P()r
    category: wk
    poll_interval: 270
    version: 1
    enabled: false
    
- climate:
    friendly_name: Thermostat
    current_temperature_code: temp_current
    current_temperature_dp: '24'
    temperature_command_code: temp_set
    temperature_command_dp: '16'
    hvac_mode_command_code: mode
    hvac_mode_command_dp: '2'
    hvac_modes:
      off: manual
      heat: auto
    min_temperature: 59.0
    max_temperature: 104.0
    precision: 1.0
    enabled: false

- switch:
    friendly_name: Power
    code: switch
    id: '1'
    entity_category: None
    restore_on_reconnect: false
    is_passive_entity: false
    enabled: true

- switch:
    friendly_name: Child Lock
    code: child_lock
    id: '40'
    entity_category: None
    restore_on_reconnect: false
    is_passive_entity: false
    enabled: true

- switch:
    friendly_name: Backlight
    code: backlight
    id: '44'
    entity_category: None
    restore_on_reconnect: false
    is_passive_entity: false
    enabled: true

- switch:
    friendly_name: Eco
    code: eco
    id: '4'
    entity_category: None
    restore_on_reconnect: false
    is_passive_entity: false
    enabled: true

- switch:
    friendly_name: Frost
    code: frost
    id: '10'
    entity_category: None
    restore_on_reconnect: false
    is_passive_entity: false
    enabled: true

- sensor:
    friendly_name: Heating
    code: valve_state
    id: '36'
    entity_category: None
    enabled: true

- sensor:
    friendly_name: Battery
    code: battery_percentage
    id: '35'
    entity_category: diagnostic
    device_class: battery
    enabled: true
